name: Fancode1 Channel

oon:
  schedule:
    - cron: '0 6 * * *'    # 12:00 PM BST
    - cron: '0 8 * * *'    # 2:00 PM BST
    - cron: '30 9 * * *'   # 3:30 PM BST
    - cron: '0 11 * * *'   # 5:00 PM BST
    - cron: '0 13 * * *'   # 7:00 PM BST
    - cron: '0 14 * * *'   # 8:00 PM BST
    - cron: '0 16 * * *'   # 10:00 PM BST
    - cron: '0 18 * * *'   # 12:00 AM BST
    - cron: '0 22 * * *'   # 4:00 AM BST
    - cron: '0 0 * * *'    # 6:00 AM BST
    - cron: '0 2 * * *'    # 8:00 AM BST
    - cron: '0 4 * * *'    # 10:00 AM BST
    - cron: '30 4 * * *'   # 10:30 AM BST
    - cron: '0 5 * * *'    # 11:00 AM BST
  workflow_dispatch: # ম্যানুয়ালি টেস্ট করার জন্য

# গিটহাব অ্যাকশনকে পুশ/রাইট করার পারমিশন দেওয়া হচ্ছে
permissions:
  contents: write

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run filter script
      run: python filter2.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Fancode1.m3u8
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto updated playlist" && git push)
