name: Auto Update Playlist

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Playlist
        run: |
          echo '#EXTM3U' > latest_movies.m3u

          PROMO='#EXTINF:-1 group-title="PROMO" tvg-logo="https://i.postimg.cc/13XVVyg3/1773936967533.png",STABLE-SPORTS TV
http://198.195.239.50:8095/StarSports2/tracks-v1a1/mono.m3u8'

          # START PROMO
          echo "$PROMO" >> latest_movies.m3u
          echo "" >> latest_movies.m3u

          # DOWNLOAD PLAYLISTS
          curl -L "https://raw.githubusercontent.com/srhady/join_telegram_chennal-livesportsplay/refs/heads/main/latest_movies.m3u" -o p1.m3u

          curl -L "https://raw.githubusercontent.com/abusaeeidx/Movie-Playlist-Auto-update/refs/heads/main/Bangla_Movies.m3u" -o p2.m3u

          curl -L "https://raw.githubusercontent.com/abusaeeidx/Movie-Playlist-Auto-update/refs/heads/main/Mix_Movies.m3u" -o p3.m3u

          # REMOVE HEADERS
          sed '/#EXTM3U/d' p1.m3u > clean1.m3u
          sed '/#EXTM3U/d' p2.m3u > clean2.m3u
          sed '/#EXTM3U/d' p3.m3u > clean3.m3u

          count=0

          merge_file () {
            while IFS= read -r line; do
              echo "$line" >> latest_movies.m3u

              if [[ "$line" == http* ]]; then
                count=$((count+1))

                # EVERY 40 CHANNELS ADD PROMO
                if (( count % 40 == 0 )); then
                  echo "$PROMO" >> latest_movies.m3u
                  echo "" >> latest_movies.m3u
                fi
              fi
            done < "$1"
          }

          merge_file clean1.m3u
          merge_file clean2.m3u
          merge_file clean3.m3u

          # END PROMO
          echo "$PROMO" >> latest_movies.m3u

          # REMOVE DUPLICATE ENTRIES
          awk '
          BEGIN { RS="#EXTINF"; ORS="" }
          !seen[$0]++
          ' latest_movies.m3u > final.m3u

          mv final.m3u latest_movies.m3u

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add latest_movies.m3u

          git commit -m "Daily Auto Update Playlist" || echo "No changes"

          git push
